import { PlanStatus, PlanType } from "redux/app/types";

const testDate = "2025-02-21T06:25:01.226Z";

export const mockPlanData: PlanType[] = [
  {
    deleted: false,
    deletedOn: testDate,
    deletedBy: "test",
    createdOn: testDate,
    modifiedOn: testDate,
    createdBy: "test",
    modifiedBy: "test",
    id: "1563ef57-f82e-5cb3-349d-14e70b744de0",
    name: "Plus",
    description: "plus description",
    amount: "2000.00",
    metadata: Object,
    isCustomPlan: false,
    billingCycleId: "56916d96-e3eb-2c4a-9815-374a9d7e5194",
    currencyId: "5c562608-5ed5-4fcc-27bd-5ef8368660f5",
    clusterId: "a094abe9-8a92-4f5b-8203-b3f168cfe796",
    tier: [
      {
        deleted: false,
        deletedOn: null,
        deletedBy: null,
        createdOn: "date",
        modifiedOn: "date",
        createdBy: "test",
        modifiedBy: null,
        id: "9fe7a27d-a539-e2ca-ddb1-d9a2d40bc11d",
        label: "silo",
        description: "silo tier",
      },
    ],
    planItem: [
      {
        deleted: false,
        deletedOn: null,
        deletedBy: null,
        createdOn: "2025-02-21T06:09:12.860Z",
        modifiedOn: "2025-02-21T06:09:12.860Z",
        createdBy: "test",
        modifiedBy: null,
        id: "105be72a-1589-17b0-7729-194ecc8c5ce8",
        name: "product",
        planItemType: 0,
        planValue: [
          {
            name: "cpq-document-hub",
            paths: "/cpq-document-hub/v4(/|$)(.*)",
            action: "install",
            domain: "",
            replicas: "1",
            blank_res: "yes",
            featureName: "CPQ Document",
            chart_version: "17.0.7",
            "ingress-rewrite-target": "true",
          },
          {
            name: "cpq-discount-service",
            paths: "/cpq-discount-service/v4(/|$)(.*)",
            action: "install",
            domain: "",
            replicas: "1",
            blank_res: "yes",
            featureName: "CPQ Discount",
            chart_version: "17.0.4",
            "ingress-rewrite-target": "true",
          },
        ],
      },
    ],
    status: PlanStatus.ACTIVE,
  },
];

export const customPlanData: PlanType[] = [
  {
    deleted: false,
    deletedOn: testDate,
    deletedBy: "test",
    createdOn: "2025-02-20T18:04:34.897Z",
    modifiedOn: "2025-02-20T18:04:34.897Z",
    createdBy: "test",
    modifiedBy: "test",
    id: "58d22ff5-73b4-1c3b-7455-f83205cc8f2e",
    name: "Standard",
    description: "some description",
    amount: "1000.00",
    metadata: Object,
    isCustomPlan: true,
    billingCycleId: "56916d96-e3eb-2c4a-9815-374a9d7e5194",
    currencyId: "5c562608-5ed5-4fcc-27bd-5ef8368660f5",
    clusterId: "fc139bb9-b9fb-6b89-cfa8-fbc3d7b45307",
    tier: [
      {
        deleted: false,
        deletedOn: null,
        deletedBy: null,
        createdOn: "date",
        modifiedOn: "date",
        createdBy: "test",
        modifiedBy: null,
        id: "9fe7a27d-a539-e2ca-ddb1-d9a2d40bc11d",
        label: "silo",
        description: "silo tier",
      },
    ],
    planItem: [
      {
        deleted: false,
        deletedOn: null,
        deletedBy: null,
        createdOn: "2025-02-20T14:52:55.865Z",
        modifiedOn: "2025-02-20T14:52:55.865Z",
        createdBy: "test",
        modifiedBy: null,
        id: "325a9698-a423-984f-6eab-00913c56e6c1",
        name: "catalog",
        planItemType: 0,
        planValue: [
          {
            name: "cpq-document-hub",
            paths: "/cpq-document-hub/v4(/|$)(.*)",
            action: "install",
            domain: "",
            replicas: "1",
            blank_res: "yes",
            featureName: "CPQ Document",
            chart_version: "17.0.7",
            "ingress-rewrite-target": "true",
          },
          {
            name: "cpq-discount-service",
            paths: "/cpq-discount-service/v4(/|$)(.*)",
            action: "install",
            domain: "",
            replicas: "1",
            blank_res: "yes",
            featureName: "CPQ",
            chart_version: "17.0.4",
            "ingress-rewrite-target": "true",
          },
        ],
      },
    ],
    status: PlanStatus.ACTIVE,
  },
];
