import { InvoiceStatus } from "Constants/enums/invoice-status.enum";
import { IBillingInvoice } from "redux/app/types/invoice.type";

export const paymentsData: IBillingInvoice[] = [
  {
    id: "1",
    invoiceId: "INV-1001",
    invoiceStatus: InvoiceStatus.PAID,
    billingCustomerId: "B123456",
    amount: "5000.0",
    tax: "500.0",
    discount: "0.0",
    payment: {
      id: "PAY001",
      paymentDate: "2025-01-20",
      amount: "5000.0",
      totalAmount: "5500.0",
      currencyCode: "US",
      taxRate: "10%",
    },
    billingCustomer: {
      tenantId: "T003",
      customerId: "C123456",
    },
    currencyCode: "",
    dueDate: "",
    startDate: "",
    endDate: "",
    invoiceDate: "",
    invoiceNo: "",
    createdOn: "",
  },
  {
    id: "2",
    invoiceId: "INV-1002",
    invoiceStatus: InvoiceStatus.PENDING,
    billingCustomerId: "B789012",
    amount: "7500.5",
    tax: "750.0",
    discount: "100.0",
    payment: {
      id: "PAY002",
      paymentDate: "2025-02-01",
      amount: "7500.5",
      totalAmount: "8250.5",
      currencyCode: "INR",
      taxRate: "10%",
    },
    billingCustomer: {
      tenantId: "T003",
      customerId: "C123456",
    },
    currencyCode: "",
    dueDate: "",
    startDate: "",
    endDate: "",
    invoiceDate: "",
    invoiceNo: "",
    createdOn: "",
  },
  {
    id: "3",
    invoiceId: "INV-1003",
    invoiceStatus: InvoiceStatus.PAID,
    billingCustomerId: "B345678",
    amount: "6200.75",
    tax: "620.08",
    discount: "0.0",
    payment: {
      id: "PAY003",
      paymentDate: "2025-02-15",
      amount: "6200.75",
      totalAmount: "6820.83",
      currencyCode: "US",
      taxRate: "10%",
    },
    billingCustomer: {
      tenantId: "T003",
      customerId: "C123456",
    },
    currencyCode: "",
    dueDate: "",
    startDate: "",
    endDate: "",
    invoiceDate: "",
    invoiceNo: "",
    createdOn: "",
  },
];
