export const RouteConstant = {
  CONFIGURATION_PLANS: "/configuration/plans",
  CONFIGURATION_PLANS_CREATE: "/configuration/plans/add-plan",
  CONFIGURATION_PLAN_EDIT: "/configuration/plans/:id/edit",
  CONFIGURATION_PLAN_ITEMS: "/configuration/plan-items",
  CONFIGURATION_PLAN_ITEMS_CREATE: "/configuration/plan-items/create",
  CONFIGURATION_PLAN_ITEMS_EDIT: "/configuration/plan-items/:id/edit",
  CONFIGURATION_PLAN_ITEMS_EDIT_FUNC: (id: string) =>
    `/configuration/plan-items/${id}/edit`,
  CONFIGURATION_TERMS_CONDITION: "/configuration/terms-condition",
  CONFIGURATION_SETTINGS: "/configuration/settings",
  BILLINGS_AND_INVOICES: "/billings-and-invoices",
  CONFIGURATION_FEATURES: "/configuration/features",
  CONFIGURATION_CLUSTERS: "/configuration/clusters",
  CONFIGURATION_BILLING: "/configuration/billing-cycles",
  DASHBOARD: "/dashboard",
  LEADS: "/leads",
  TENANTS: "/tenants",
  TENANTS_CREATE: "/tenants/create-tenant",
  TENANTS_CREATE_FROM_LEAD: "/tenants/create-tenant/:id",
  TENANT_VIEW_FROM_DASHBOARD: "/tenants/:id",
  NOT_AUTHORIZED: "/not-authorized",
  TENANTS_EDIT: "/tenants/:id/edit",
};
